# Generated by Django 4.0.6 on 2024-02-16 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_type', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
