version: "3"

services:
  frontend:
    build:
      context: client
    container_name: shareCanadaHome-client-container
    tty: true
    volumes:
      - ./client:/client
    ports:
      - 3000:3000
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev

  backend:
    build:
      context: server
    container_name: shareCanadaHome-server-container
    tty: true
    volumes:
      - ./server:/server
    ports:
      - 8000:8000
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    command: > 
      bash -c "python ./manage.py makemigrations propertyhub && 
              python ./manage.py migrate &&  
              echo \"from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'adminadmin')\" | python manage.py shell &&
              python ./manage.py runserver 0:8000"

  backend_scripts:
    build:
      context: server/scripts
    container_name: shareCanadaHome-server-scripts-container
    tty: true
    volumes:
      - ./server/scripts:/scripts
    # command: > 
    #   bash -c "ls && pwd && python ./site_scraper.py"
    networks:
      app_net:
        ipv4_address: 172.30.0.4

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24