version: "3"

services:
  frontend:
    build:
      context: client
    container_name: client-container
    tty: true
    volumes:
      - ./client:/client
      - front_node_modules:/client/node_modules
    ports:
      - 3000:3000
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    environment:
      - WATCHPACK_POLLING=true
    # command: npm install

  backend:
    build:
      context: server
    container_name: server-container
    tty: true
    volumes:
      - ./server:/server
    ports:
      - 8000:8000
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    command: >
      bash -c  "python ./manage.py makemigrations propertyhub && 
                python ./manage.py makemigrations contactus && 
                python ./manage.py migrate &&  
                python ./manage.py superuser &&
                python ./manage.py runserver 0:8000"

  backend_job:
    build:
      context: server/scripts
    container_name: job-container
    tty: true
    volumes:
      - ./server/scripts:/scripts
    networks:
      app_net:
        ipv4_address: 172.30.0.4

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

volumes:
  front_node_modules:
