# Generated by Django 4.0.6 on 2024-01-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
