# Generated by Django 4.0.6 on 2024-02-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='reference',
            field=models.CharField(default='Waccanet', max_length=50),
        ),
    ]
