# Generated by Django 4.0.6 on 2024-01-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyhub', '0002_image_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
