# Generated by Django 4.0.6 on 2024-01-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyhub', '0003_image_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='file_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
