# Generated by Django 4.0.6 on 2024-01-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyhub', '0004_remove_image_image_alter_image_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_data',
        ),
        migrations.AddField(
            model_name='image',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
